### ISSUE TITLE
Error running sample recording code

### ISSUE THREAD

**Issue by raivisdejus** [henrikschnor/pasimple#3]
This wrapper seems exactly like the thing that I need, when tried to run the example code 

```
from pasimple import record_wav, play_wav

# Record 5 seconds of audio from the default recording device
record_wav('/tmp/test_recording.wav', 5)
```
I get the following error `NameError: name 'pasimple' is not defined. Did you mean: 'pa_simple'?`

Installed with `pip3 install pasimple` in a python virtual environment

**Comment by henrikschnor** [comment]
You are right, there seems to be an issue with the wrapper. I just pushed a possible fix to GitHub and can update the PyPi package later today.

**Comment by raivisdejus** [comment]
I can confirm, that fix worked. 

Great, simple wrapper, thanks!

**Comment by henrikschnor** [comment]
Thank you for reporting the issue and confirming the fix! :-)
I just uploaded the fixed version to PyPI.
